# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  ergogen_generate:
      name: Generate
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Use Node Version 14
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install dependencies
          run: npm install
        - name: Run Ergogen
          run: npm run gen
        - name: Add the output to the repo
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add V1\ergogen\output
            git commit -m "ran Ergogen"
            git push